#n1 = int(input('Digite um numero'))
#print(n1), 'e seu tipo é', print(type(n1))
#n2 = float(input('Digite outro'))
#print(n2), 'e seu tipo é', print(type(n2))
#n3 = str(input('Digite mais um'))
#print(n3), 'e seu tipo é', print(type(n3))
#n4 = bool(input('O último'))
#print(n4), 'e seu tipo é', print(type(n4))

a = input('Digite algo')
print('O tipo primitivo desse valor é', type(a))
print('É alfabetico?', a.isalpha())
print('É numerico?', a.isnumeric())
print('É somente espaços?', a.isspace())
print('É alfanumerico?', a.isalnum())
print('É maiuscula?', a.isupper())
print('É minuscula?', a.islower())
print('Esta capitalizada?', a.istitle())
